name: IntegrationTests
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "pipelines/github-action/github-action.integration-tests.yml"
      - ".github/workflows/github-action.integration-tests.yml"    

  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "pipelines/github-action/github-action.integration-tests.yml"
      - ".github/workflows/github-action.integration-tests.yml" 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "detect-secrets"
  integration-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      configurationFile: 'integration-tests.env'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Pre-requisites
        run: |
          pipelines/utils/mtstool.sh -a install -c ${{ env.configurationFile }} -e true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Integration Tests 
        run: |
          pipelines/utils/mtstool.sh -a integration -c ${{ env.configurationFile }} -e true -s true
          
